=head1 NAME

Teamspeak::Web - Web Interface to a Teamspeak Server.

=head1 SYNOPSIS

  $tsh = Teamspeak::Web->new();
  $tsh->connect( $login, $pwd );

The Interface depends on the L<"Teamspeak">->type().
See L<"Teamspeak::Telnet::Channel">, L<"Teamspeak::SQL::Channel">...

=head1 CLASS METHODS

=head2 new( host => 'localhost', port => 14534 )

This creates the Object.

=head2 connect( slogin => $slogin, pwd => $pwd )
=head2 connect( login => $login, pwd => $pwd )

This connects to the Webfrontend and fill out the login-form to connect as
superadmin or normal admin.

=head2 _slogin( $login, $pwd )

Login at the Webfrontend with superadmin-rights.

=cut

